apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    readinessProbe:
      httpGet:
        path: /
        port: 80
    ports:
      - containerPort: 80
