apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: dotnetapi
  name: dotnetapi
spec:
  containers:
  - image: romeelk/dotnetapi
    name: dotnetapi
    env:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
    ports:
    - containerPort: 8080
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
